#!/bin/bash
TASK_NAME = SST-2
GLUE_DIR = /home/ben/Documents/CERN/rebuttal_iclr/GLUE

/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/31000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/32000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/33000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/34000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/35000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/36000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/37000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/38000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/39000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/40000000000.0.json > ./logs.txt
/home/ben/anaconda3/envs/CERN/bin/python run_classifier.py   --task_name $TASK_NAME   --do_train   --do_eval   --do_lower_case   --data_dir $GLUE_DIR/$TASK_NAME   --bert_model bert-base-uncased   --max_seq_length 128   --train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3.0   --output_dir ../testing/   --config_dir=../test_configs/45000000000.0.json > ./logs.txt
